# Generated by Django 3.1.7 on 2021-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_userprofile_is_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='HDD',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='Ram',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
