# Generated by Django 3.1.7 on 2021-03-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210311_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='allocation_id',
            new_name='allocated_to',
        ),
    ]
